name = "StdlibRegistryCompatUpdater"
uuid = "f4500fdb-a4ad-4c09-b0b3-caa244d2a8f5"
authors = ["KristofferC <kristoffer.carlsson@juliacomputing.com>"]
version = "0.1.0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
RegistryTools = "d1eb7eb1-105f-429d-abf5-b0f65cb9e2c4"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
